import { Component, Input, OnInit } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-playlist-popout',
  templateUrl: './playlist-popout.component.html',
  styleUrls: ['./playlist-popout.component.css'],
})
export class PlaylistPopoutComponent implements OnInit {
  constructor(private modalService: NgbModal) {}

  @Input() playlistName = 'Music Playlist';
  @Input() playlistLen = '2:33:17';
  @Input() numSongs = '28';
  @Input() playlistCrtr = 'Chuck Berry';
  @Input() playlistItems: string[][] = [];
	open(content): void {
    this.modalService.open(content, { modalDialogClass: 'hidden-modal' });
  }
  ngOnInit(): void {
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
    this.playlistItems.push([
      'https://picsum.photos/200',
      'https://picsum.photos/200',
      'songName',
      'artistName',
      'albumName',
    ]);
  }
}
